<?php

namespace Eril\Auth;

use InvalidArgumentException;
use RuntimeException;

final class Auth
{
    private static ?AuthManager $manager = null;

    /**
     * Configure the authentication system.
     *
     * This method should usually be called once during application bootstrap.
     *
     * Example:
     *
     * Auth::configure([
     *     'db' => $pdo,
     *     'user_table' => 'users',
     *     'id_field' => 'id',
     *     'name_field' => 'name',
     *     'login_field' => 'email',
     *     'password_field' => 'password',
     *     'role_field' => 'role',
     *     'session_name' => 'auth_user',
     *     'session_lifetime' => 3600,
     *     'remember_enabled' => true,
     *     'remember_cookie' => 'remember_token',
     *     'remember_token_field' => 'remember_token',
     *     'remember_days' => 30,
     * ]);
     *
     * Available options:
     *
     * @param array{
     *     db:\PDO|callable,
     *     user_table?:string,
     *     id_field?:string,
     *     name_field?:string,
     *     login_field?:string,
     *     password_field?:string,
     *     role_field?:string|null,
     *     permissions?:array,
     *     session_name?:string,
     *     session_lifetime?:int,
     *     remember_enabled?:bool,
     *     remember_cookie?:string,
     *     remember_token_field?:string|null,
     *     remember_selector_field?:string|null,
     *     remember_days?:int
     * } $config
     *
     * Option details:
     *
     * - db:
     *   PDO instance or callable returning a PDO instance.
     *
     * - user_table:
     *   Database table where users are stored.
     *
     * - id_field:
     *   User primary key column.
     *
     * - name_field:
     *   User display name column.
     *
     * - login_field:
     *   Column used for authentication. Common values: email, username, phone.
     *
     * - password_field:
     *   Column containing the password hash generated by password_hash().
     *
     * - role_field:
     *   Column containing the user role. Set null to disable role checks.
     *
     * - session_name:
     *   Session key used to store the authenticated user payload.
     *
     * - session_lifetime:
     *   Session lifetime in seconds.
     *
     * - remember_enabled:
     *   Enables or disables remember-me support.
     *
     * - remember_cookie:
     *   Cookie name used by remember-me.
     *
     * - remember_token_field:
     *   Column used to store the hashed remember-me token.
     *   Required when remember_enabled is true.
     *
     * - remember_selector_field:
     *   Reserved for future selector/token remember-me strategy.
     *
     * - remember_days:
     *   Remember-me cookie lifetime in days.
     *
     * @throws InvalidArgumentException
     */
    public static function configure(array $config): void
    {
        $authConfig = AuthConfig::fromArray($config);
        $pdo = new PdoResolver($authConfig->db());

        self::$manager = new AuthManager(
            config: $authConfig,
            pdo: $pdo,
            session: new SessionManager(),
        );

        Authorization::configure($authConfig, self::$manager);

        self::$manager->boot();
    }

    /**
     * Load authentication configuration from a PHP file.
     *
     * The file must return an array accepted by Auth::configure().
     *
     * Example:
     *
     * Auth::loadConfig(__DIR__ . '/config/auth.php');
     *
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    public static function loadConfig(string $path): void
    {
        if (!is_file($path)) {
            throw new InvalidArgumentException("Auth config file not found: {$path}");
        }

        $config = require $path;

        if (!is_array($config)) {
            throw new RuntimeException('Auth config file must return an array.');
        }

        self::configure($config);
    }

    /**
     * Attempt to authenticate a user using login and password.
     *
     * The login value is matched against the configured login_field.
     *
     * @return AuthUser|false
     */
    public static function attempt(string $login, string $password): AuthUser|false
    {
        return self::manager()->attempt($login, $password);
    }

    /**
     * Manually login a user using a database row or compatible array.
     */
    public static function login(array $user): AuthUser
    {
        return self::manager()->login($user);
    }

    /**
     * Logout the current authenticated user.
     */
    public static function logout(): void
    {
        self::manager()->logout();
    }

    /**
     * Determine if there is an authenticated user.
     */
    public static function check(): bool
    {
        return self::manager()->check();
    }

    /**
     * Get the current authenticated user.
     */
    public static function user(): ?AuthUser
    {
        return self::manager()->user();
    }

    /**
     * Get the current authenticated user id.
     */
    public static function id(): int|string|null
    {
        return self::manager()->id();
    }

    /**
     * Determine if the authenticated user has one of the given roles.
     */
    public static function hasRole(string $role, string ...$roles): bool
    {
        return self::manager()->hasRole($role, ...$roles);
    }

    public static function can(string $permission): bool
    {
        return Authorization::can($permission);
    }

    public static function cannot(string $permission): bool
    {
        return Authorization::cannot($permission);
    }

    public static function authorize(string $permission): void
    {
        Authorization::authorize($permission);
    }

    /**
     * Remember the current authenticated user using a persistent cookie.
     */
    public static function rememberUser(): void
    {
        self::manager()->rememberUser();
    }

    /**
     * Get the last authentication error.
     */
    public static function error(): ?string
    {
        return self::manager()->error();
    }

    /**
     * Diagnose current authentication configuration and database schema.
     *
     * Auth must be configured before calling this method.
     *
     * @return array<string, array{ok:bool, message:string}>
     */
    public static function diagnose(): array
    {
        return self::manager()->diagnose();
    }


    private static function manager(): AuthManager
    {
        if (!self::$manager) {
            throw new RuntimeException('Auth is not configured. Call Auth::configure() first.');
        }

        return self::$manager;
    }
}
